name: start ChaCon
on:
#for test
  issue_comment:
    types: [created]
  schedule:
    - cron:  '0 */8 * * *'    
env:
  isecFold: 'insec/'
  workFold: '/opt/'
  repoName: 'CovCon'  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.head_ref }} 
    - name: base install
      run: |
            sudo apt-get update
            sudo apt-get install -y p7zip-full unzip wget iftop nmon
            (cd ${{env.isecFold}}&&sudo 7z x archive.7z -p${{secrets.GIT_PASS}} -o${{env.workFold}})    
            sudo apt-get install -y git python3 python3-pandas python3-pip python3-setuptools
            sudo apt-get install -y python3-dev python3-pip python3-venv python3-wheel
            sudo pip3 install wheel
            sudo -H pip3 install --ignore-installed PyYAML 
            sudo pip3 install pybadges
            mkdir /tmp/works
    - name: base works
      if: ${{ github.event_name == 'schedule' || contains(github.event.comment.body, 'testWorks') }}
      run: |
           sudo python3 ${{env.workFold}}${{env.repoName}}_1.py ${{env.workFold}}
    - name: hands works
      if: ${{ github.event_name == 'issue_comment' && contains(github.event.comment.body, 'handWorks') }}
      run: |
           sudo apt-get install -y tmate openssh-client python3-pip python3-setuptools
           sudo pip3 install pytelegrambotapi --upgrade	  
           sudo npm install --global http-server
           echo -e 'y\n'|sudo ssh-keygen -q -t rsa -N "" -f /root/.ssh/id_rsa	  
           sudo python3 ${{env.workFold}}sl.py ${{env.repoName}}  
